#!/bin/bash -eux
# see: https://docs.docker.com/desktop/install/windows-install/#install-from-the-command-line

testPrefix="$(basename "$0")"
log() {
  echo "[$testPrefix] $*"
}

log "Downloading..."
curl --output installer.exe --url 'https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe'

log "Starting installer..."
./installer.exe install --accept-license --no-windows-containers

log "Starting docker desktop..."
'C:\Program Files\Docker\Docker\Docker for Windows.exe'
while ! docker info; do sleep 1; done

log "Complete."
