#!/bin/bash -eu
set -o pipefail

testPrefix="$(basename "$0")"
log() {
  echo "[$testPrefix] $*"
}

log "Running shellcheck on all scripts..."
cat <(git grep -l '^#!.*sh\b') <(git ls-files '*.bash') | xargs shellcheck -a -x lib.bash

# test scenarios:
# DONE - happy path
# TODO - upgrade image doesn't start
# TODO - maybe if multiple images are started at once?
# DONE - out of space while upgrading
# TODO - interrupted part-way through (how to randomise this?)
# SKIP - run on windows, macOS; ideally in CI
# TODO - script importing an example DB into the 9.6 container and then running the upgrade
# TODO - read-only target fs (is this useful?)

# TODO review all steps and possible failure modes at https://www.postgresql.org/docs/current/pgupgrade.html
# DONE do we need a upgrade-started flag file?

log "All OK!"
