#!/bin/bash -eu
name="$1"
hash="$(docker ps | awk '$2 ~ "central-'"$name"'" { print $1 }')"
docker logs "central-${name}-1"
exitCode="$(docker inspect "$hash" --format='{{.State.ExitCode}}')"
exit "$exitCode"
