#!/bin/bash -eu

log() { echo "[$(basename "$0")] $*"; }

if ! [[ -f "$configPath" ]]; then
  log "No config found; creating now..."
  cat >"$configPath" <<EOF
[http]
  [http.retry]
    max = 5
    delay = "2s"

[registry."docker.io"]
  http = true
  # Sets explicit timeouts for registry operations
  timeout = "30s"
EOF
fi

log "--- Current docker buildx config ---"
cat "$configPath"
log "------------------------------------"

log "Completed OK."
