#!/bin/bash -eu

log() { echo "[$(basename "$0")] $*"; }

if ! [[ ${CI-} = true ]]; then
  log "You're not running in CI.  You probably don't want to run this script."
  exit 1
fi

configPath=/etc/docker/buildkitd.toml

if ! [[ -f "$configPath" ]]; then
  log "No config found; creating now..."
  sudo cat >"$configPath" <<EOF
[http]
  [http.retry]
    max = 5
    delay = "2s"

[registry."docker.io"]
  http = true
  # Sets explicit timeouts for registry operations
  timeout = "30s"
EOF
fi

log "--- Current docker buildx config ---"
cat "$configPath"
log "------------------------------------"

log "Completed OK."
