#!/bin/bash -eu

# Test that running out of disk space during the upgrade stage is
# communicated via the upgrade log file.

log "Restricting target volume size..."
volumeOpts="size=1m"

. ./lib.bash

log "Upgrading central..." # see: https://docs.getodk.org/central-upgrade/
git_checkout "$targetBranch"

rebuild_and_restart_containers

confirm_postgres_version ECONNREFUSED
upgradeLogFile="./files/postgres14/upgrade/upgrade-postgres.log"
if ! grep -E 'UTC .* FATAL: .*: No space left on device$' "$upgradeLogFile"; then
  log "------------------ $upgradeLogFile ------------------"
  cat "$upgradeLogFile"
  log "-------------------------------------------------------"
  log "!!!"
  log "!!! Upgrade failed for unexpected reason!  Please review logs above."
  log "!!!"
  exit 1
fi

log "Test passed OK!"
