#!/bin/bash -eux

testPrefix="$(basename "$0")"
log() {
  echo "[$testPrefix] $*"
}

ls -al .

log "Creating cleanup flag file..."
touch ./postgres-upgrade-logs/delete-old-postgres9.6-data-on-next-restart

log "Starting cleanup..."
docker-compose up --abort-on-container-exit postgres

# TODO test that the space was saved, or that the volume has gone

log "Cleanup completed OK."
