#!/bin/bash -eu

# Test that a fresh install with the latest central version will
# start normally.

INITIAL_VERSION="upgrade-pg-14-official"

. ./lib.bash

check_for_dependencies
configure_environment
clone_central_repo
check_for_dirty_docker

log "Starting $targetBranch..."
docker compose build
docker compose up --remove-orphans --detach

wait_for_service_container

confirm_postgres_version 14
confirm_backend_running_ok

exec_in_service_container seed-db.js
test_restart

log "Test passed OK!"
