#!/bin/bash -eu

# Test that running out of disk space during the upgrade stage is
# communicated via the upgrade log file.

. ./lib.bash
setup_standard

log "Upgrading central..." # see: https://docs.getodk.org/central-upgrade/
git_checkout "$targetVersion"

log "Restricting target volume size..."
cat >>docker-compose.yml <<EOF
    driver: local
    driver_opts:
      device: ./files/postgres-14/volume-postgres_14
      type: tmpfs
      o: "size=1m"
EOF

rebuild_and_restart_containers

confirm_postgres_version ECONNREFUSED
upgradeLogFile="./postgres-14-upgrade/upgrade-postgres.log"
if ! grep -E 'UTC .* FATAL: .*: No space left on device$' "$upgradeLogFile"; then
  log "------------------ $upgradeLogFile ------------------"
  cat "$upgradeLogFile"
  log "-------------------------------------------------------"
  log "!!!"
  log "!!! Upgrade failed for unexpected reason!  Please review logs above."
  log "!!!"
  exit 1
fi

log "Test passed OK!"
