#!/bin/bash -eu

# Test that a successful migration will cause a specific file to be
# created in the shared migation-logs directory.

. ./lib.bash
setup_standard

log "Upgrading central..." # see: https://docs.getodk.org/central-upgrade/
git_checkout "$targetVersion"
rebuild_and_restart_containers

confirm_postgres_version 14
confirm_seed_data
confirm_postgres_version 14
confirm_backend_running_ok

if ! [[ -f ./migration-logs/migrate-postgres-9.6-14.completed.ok ]]; then
  log "!!!"
  log "!!! Migration success flag file not found!"
  log "!!!"
  exit 1
fi

log "Test passed OK!"
