#!/bin/bash -eux

. ./lib.bash
setup_standard

log "Upgrading central..." # see: https://docs.getodk.org/central-upgrade/
git checkout "$targetVersion"
git show --pretty=oneline --summary
log "Restricting target volume size..."
cat >>docker-compose.yml <<EOF
    driver: local
    driver_opts:
      device: ./files/postgres-14/volume-pg14
      type: tmpfs
      o: "size=45m"
EOF

git submodule update -i --jobs 16
dev_speed_patch
docker-compose build
dev_speed_unpatch

log "Restarting containers..."
docker-compose stop
docker-compose up --remove-orphans --detach

wait_for_service_container

confirm_postgres_version ECONNREFUSED
migrationLogFile="./migration-logs/migrate-postgres-9.6-14.log"
if ! grep -E '^pg_restore: error: could not execute query: ERROR:  could not write to file ".*": No space left on device$' "$migrationLogFile"; then
  log "------------------ $migrationLogFile ------------------"
  cat "$migrationLogFile"
  log "-------------------------------------------------------"
  log "!!!"
  log "!!! Migration failed for unexpected reason!  Please review logs above."
  log "!!!"
  exit 1
fi

log "Test passed OK!"
