#!/bin/bash -eux

cd "$ODK_PG_UPGRADE_BASE_DIR"

testPrefix="$(basename "$0")"
log() {
  echo "[$testPrefix] $*"
}

log "Creating cleanup flag file..."
touch ./postgres-upgrade-logs/delete-old-postgres9.6-data-on-next-restart

log "Starting cleanup..."
docker-compose up --abort-on-container-exit postgres

# TODO test that the space was saved, or that the volume has gone

log "Cleanup completed OK."
