#!/bin/bash -eu

# Test that running out of disk space during the migration stage is
# communicated via the migration log file.

. ./lib.bash
setup_standard

log "Upgrading central..." # see: https://docs.getodk.org/central-upgrade/
git_checkout "$targetVersion"

log "Restricting target volume size..."
cat >>docker-compose.yml <<EOF
    driver: local
    driver_opts:
      device: ./files/postgres-14/volume-pg14
      type: tmpfs
      o: "size=45m"
EOF

rebuild_and_restart_containers

confirm_postgres_version ECONNREFUSED
migrationLogFile="./migration-logs/migrate-postgres-9.6-14.log"
if ! grep -E '^pg_restore: error: could not execute query: ERROR:  could not write to file ".*": No space left on device$' "$migrationLogFile"; then
  log "------------------ $migrationLogFile ------------------"
  cat "$migrationLogFile"
  log "-------------------------------------------------------"
  log "!!!"
  log "!!! Migration failed for unexpected reason!  Please review logs above."
  log "!!!"
  exit 1
fi

log "Test passed OK!"
