#!/bin/bash -eux

. ./lib.bash
setup_standard

log "Upgrading central..." # see: https://docs.getodk.org/central-upgrade/
git checkout "$targetVersion"
git show --pretty=oneline --summary
git submodule update -i --jobs 16
dev_speed_patch
docker-compose build
dev_speed_unpatch

log "Restarting containers..."
docker-compose stop
docker-compose up --remove-orphans --detach

wait_for_service_container

confirm_postgres_version 14
confirm_seed_data
confirm_postgres_version 14
confirm_backend_running_ok

migrationLogFile="./migration-logs/migrate-postgres-9.6-14.log"
if ! [[ -f "$migrationLogFile" ]]; then
  log "!!!"
  log "!!! Migration success flag not found!"
  log "!!!"
  exit 1
fi

log "Test passed OK!"
