#!/bin/bash -eu

# Test that a successful upgrade will cause a specific file to be
# created in the shared migation-logs directory.

create_sized_vol() {
  local sizeMb="$1"
  local diskImg="./temp-disk.img"
  log "[create_sized_vol] Creating volume with size: ${sizeMb}MB..."
  dd if=/dev/zero of="$diskImg" bs=1M count="$sizeMb"
  mkfs.ext4 -F "$diskImg"
  mkdir -p ./files/postgres14/volume-postgres14
  log "[create_sized_vol] Mounting loopback image file; this may required sudo..."
  sudo mount -o loop "$diskImg" ./files/postgres14/volume-postgres14
  log "[create_sized_vol] Revoking sudo permissions..."
  sudo -k
}

. ./lib.bash
# Extra blob: 250 MB; allow for double that.
create_sized_vol 500
setup_standard

log "Creating a massive blob..."
exec_in_service_container create-blob.js

log "Upgrading central..." # see: https://docs.getodk.org/central-upgrade/
git_checkout "$targetBranch"

log "Rebuilding and restarting containers..."
rebuild_and_restart_containers

confirm_postgres_version 18
confirm_seed_data
confirm_postgres_version 18
confirm_backend_running_ok
log "Containers rebuilt and restarted OK."

if ! [[ -f ./files/postgres14/upgrade/upgrade-successful ]]; then
  log "!!!"
  log "!!! ERROR: Upgrade success flag file not found!"
  log "!!!"
  exit 1
fi

log "Upgrade completed OK!"
