#!/bin/bash -eu

# Test that a successful migration will cause a specific file to be
# created in the shared migation-logs directory.

. ./lib.bash
setup_standard

log "Upgrading central..." # see: https://docs.getodk.org/central-upgrade/
git_checkout "$targetVersion"

log "Restricting target volume size to confirm we don't need triple size..."
cat >>docker-compose.yml <<EOF
    driver: local
    driver_opts:
      device: ./files/postgres-15/volume-pg15
      type: tmpfs
      o: "size=50m"
EOF

rebuild_and_restart_containers

confirm_postgres_version 15
confirm_seed_data
confirm_postgres_version 15
confirm_backend_running_ok

if ! [[ -f ./migration-logs/migrate-postgres-9.6-15.completed.ok ]]; then
  log "!!!"
  log "!!! Migration success flag file not found!"
  log "!!!"
  exit 1
fi

log "Test passed OK!"
