#!/bin/bash -eu
set -o pipefail

logPrefix="[$0]"
log() { echo "$logPrefix $*"; }

tmpfile="$(mktemp)"

log "Checking for orphaned volumes..."
docker volume ls --filter "dangling=true" -q | xargs -I{} bash -c 'printf "%-48s %s\n" "{}" "$(docker volume inspect --format "{{.CreatedAt}}" "{}")"' | tee "$tmpfile"

count="$(wc -l <"$tmpfile")"
if [[ "$count" = 0 ]]; then
  log "No orphaned volumes found - everything is OK."
  exit
fi

log "!!!"
log "!!! Orphaned docker volumes were found!"
log "!!!"
log "!!! Cross-reference volume names with previous logs to understand where they originated."
log "!!!"
exit 1
