#!/bin/bash -eu
set -o pipefail

scriptDir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

logPrefix="[$0]"
log() { echo "$logPrefix $*"; }

tmpfile="$(mktemp)"

log "Checking for orphaned volumes..."
# shellcheck disable=SC2016
docker volume ls --filter "dangling=true" -q \
| xargs -I{} bash -c 'printf "%-48s %s\n" "$1" "$(docker volume inspect --format "{{.CreatedAt}}" "$1")"' _ {} \
| tee "$tmpfile"

count="$(wc -l <"$tmpfile")"
if [[ "$count" = 0 ]]; then
  log "No orphaned volumes found - everything is OK."
  exit
fi

ownerLog="$scriptDir/.volume-owners"
log "--- DEBUG: $ownerLog ---"
if [[ -f "$ownerLog" ]]; then
  cat "$ownerLog"
else
  log "(file not found)"
fi
log "--- DEBUG ---"

log "!!!"
log "!!! Orphaned docker volumes were found!"
log "!!!"
log "!!! Cross-reference volume names with previous logs to understand where they originated."
log "!!!"
exit 1
