#!/bin/bash -eu
set -o pipefail

scriptDir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

logPrefix="[$0]"
log() { echo "$logPrefix $*"; }

tmpfile="$(mktemp)"

log "Checking for orphaned volumes..."
pgOrphan=false
# shellcheck disable=SC2016
for vol in $(docker volume ls --filter "dangling=true" -q); do
  if grep "^vol:$vol " "$scriptDir/.owners" | grep -Ev "container:central-(enketo|nginx)-1" >/dev/null; then
    pgOrphan=true
    log "!!!"
    log "!!! $vol was previously owned by"
    grep "^vol:$vol " "$scriptDir/.owners" | awk -v prefix="$logPrefix" '{ gsub("container:", "", $2); print prefix " !!! - " $2 }'
  fi
done

if [[ "$pgOrphan" = false ]]; then
  log "No unexpected orphans found - everything looks OK."
  exit
fi

log "!!!"
log "!!! Orphaned docker volumes were found!"
log "!!!"
log "!!! Cross-reference volume names with previous logs to understand where they originated."
log "!!!"
exit 1
