#!/bin/bash -eu
set -o pipefail

logPrefix="[$0]"
log() { echo "$logPrefix $*"; }

for vol in $(docker volume ls -q); do
  log "  vol: $vol"
  containers="$(docker ps -a --filter "volume=$vol" --format "$logPrefix        - {{.Names}}")"
  if [[ -n "$containers" ]]; then
    printf "$containers\n"
  else
    log "       -- ORPHANED --"
  fi
done
